import type { DeploymentProfile } from "./types";

export const sharedCloudProfile: DeploymentProfile = {
  id: "deploy-shared-cloud",
  name: "Shared Managed Cloud",
  tier: "shared-cloud",
  description: "For consumers, startups, and developer ecosystems. Managed updates, standard telemetry, public app catalog.",
  features: {
    multiWorkspace: false,
    approvalWorkflows: false,
    dualControl: false,
    committeeApproval: false,
    spendLimits: true,
    auditExport: true,
    evidencePackaging: false,
    serviceIdentities: false,
    agentIdentities: false,
    customPolicies: false,
    adminConsole: false,
    realTimeOps: false,
    offlineSigning: false,
    hsmIntegration: false,
    mpcCustody: false,
  },
  restrictions: {
    maxWorkspaces: 1,
    maxAccountsPerWorkspace: 10,
    maxAppsInCatalog: null,
    allowExternalApps: true,
    allowCrossWorkspaceTransfers: false,
    requireKyc: false,
  },
  custodyOptions: ["software", "hardware"],
  defaultCustody: "software",
  catalogMode: "public",
  compliance: {
    auditRetentionDays: 90,
    requireApprovalEvidence: false,
    requireSigningEvidence: false,
  },
  createdAt: Date.now(),
};

export const dedicatedTenantProfile: DeploymentProfile = {
  id: "deploy-dedicated-tenant",
  name: "Dedicated Managed Tenant",
  tier: "dedicated-tenant",
  description: "For regulated enterprises and institutional operators. Tenant isolation, private catalog, policy administration.",
  features: {
    multiWorkspace: true,
    approvalWorkflows: true,
    dualControl: true,
    committeeApproval: false,
    spendLimits: true,
    auditExport: true,
    evidencePackaging: true,
    serviceIdentities: true,
    agentIdentities: false,
    customPolicies: true,
    adminConsole: true,
    realTimeOps: true,
    offlineSigning: false,
    hsmIntegration: true,
    mpcCustody: true,
  },
  restrictions: {
    maxWorkspaces: 50,
    maxAccountsPerWorkspace: 100,
    maxAppsInCatalog: 200,
    allowExternalApps: true,
    allowCrossWorkspaceTransfers: true,
    requireKyc: true,
  },
  custodyOptions: ["software", "hardware", "hsm", "mpc"],
  defaultCustody: "hardware",
  catalogMode: "private",
  compliance: {
    auditRetentionDays: 365,
    requireApprovalEvidence: true,
    requireSigningEvidence: true,
    reportingFrequency: "monthly",
  },
  createdAt: Date.now(),
};

export const sovereignCloudProfile: DeploymentProfile = {
  id: "deploy-sovereign-cloud",
  name: "Sovereign Cloud",
  tier: "sovereign-cloud",
  description: "For ministries, public institutions, and critical regulated sectors. Regional hosting, deployment-specific controls.",
  features: {
    multiWorkspace: true,
    approvalWorkflows: true,
    dualControl: true,
    committeeApproval: true,
    spendLimits: true,
    auditExport: true,
    evidencePackaging: true,
    serviceIdentities: true,
    agentIdentities: true,
    customPolicies: true,
    adminConsole: true,
    realTimeOps: true,
    offlineSigning: true,
    hsmIntegration: true,
    mpcCustody: true,
  },
  restrictions: {
    maxWorkspaces: null,
    maxAccountsPerWorkspace: null,
    maxAppsInCatalog: null,
    allowExternalApps: false,
    allowCrossWorkspaceTransfers: true,
    requireKyc: true,
    dataResidency: "sovereign",
  },
  custodyOptions: ["hardware", "hsm", "mpc", "offline"],
  defaultCustody: "hsm",
  catalogMode: "restricted",
  compliance: {
    auditRetentionDays: 2555, // 7 years
    requireApprovalEvidence: true,
    requireSigningEvidence: true,
    regulatoryFramework: "ADGM-DLT",
    reportingFrequency: "weekly",
  },
  createdAt: Date.now(),
};

export const selfHostedProfile: DeploymentProfile = {
  id: "deploy-self-hosted",
  name: "Self-Hosted / On-Prem",
  tier: "self-hosted",
  description: "For highly regulated institutions and defense-adjacent operators. Self-operated control plane, isolated distribution.",
  features: {
    multiWorkspace: true,
    approvalWorkflows: true,
    dualControl: true,
    committeeApproval: true,
    spendLimits: true,
    auditExport: true,
    evidencePackaging: true,
    serviceIdentities: true,
    agentIdentities: true,
    customPolicies: true,
    adminConsole: true,
    realTimeOps: true,
    offlineSigning: true,
    hsmIntegration: true,
    mpcCustody: true,
  },
  restrictions: {
    maxWorkspaces: null,
    maxAccountsPerWorkspace: null,
    maxAppsInCatalog: null,
    allowExternalApps: false,
    allowCrossWorkspaceTransfers: true,
    requireKyc: true,
  },
  custodyOptions: ["hardware", "hsm", "offline"],
  defaultCustody: "hsm",
  catalogMode: "isolated",
  compliance: {
    auditRetentionDays: 3650, // 10 years
    requireApprovalEvidence: true,
    requireSigningEvidence: true,
    reportingFrequency: "daily",
  },
  createdAt: Date.now(),
};

export const airGappedProfile: DeploymentProfile = {
  id: "deploy-air-gapped",
  name: "Air-Gapped / High-Assurance",
  tier: "air-gapped",
  description: "For top-tier sovereign and institutional operations. Restricted network, offline approval, HSM signing.",
  features: {
    multiWorkspace: true,
    approvalWorkflows: true,
    dualControl: true,
    committeeApproval: true,
    spendLimits: true,
    auditExport: true,
    evidencePackaging: true,
    serviceIdentities: true,
    agentIdentities: true,
    customPolicies: true,
    adminConsole: true,
    realTimeOps: false, // No network
    offlineSigning: true,
    hsmIntegration: true,
    mpcCustody: false, // Requires network
  },
  restrictions: {
    maxWorkspaces: null,
    maxAccountsPerWorkspace: null,
    maxAppsInCatalog: null,
    allowExternalApps: false,
    allowCrossWorkspaceTransfers: false,
    requireKyc: true,
  },
  custodyOptions: ["hsm", "offline"],
  defaultCustody: "offline",
  catalogMode: "isolated",
  compliance: {
    auditRetentionDays: 3650,
    requireApprovalEvidence: true,
    requireSigningEvidence: true,
    reportingFrequency: "daily",
  },
  createdAt: Date.now(),
};

export const ALL_PROFILES: DeploymentProfile[] = [
  sharedCloudProfile,
  dedicatedTenantProfile,
  sovereignCloudProfile,
  selfHostedProfile,
  airGappedProfile,
];

export function getDeploymentProfile(tier: string): DeploymentProfile {
  const profile = ALL_PROFILES.find((p) => p.tier === tier);
  return profile ?? sharedCloudProfile;
}
